### ISSUE TITLE
router.getReverseRoute() doesn't add ninja.context to absolute paths and routing doesn't work for relative paths

### ISSUE THREAD

**Issue by zoranzaric** [ninjaframework/ninja#151]
Example code: https://github.com/zoranzaric/ninja-playground/tree/routing-problems

The provided code demonstrates, that router.getReverRoute() doesn't add ninja.context to routes with absolute paths ("/").  This works for the second route, which is relative ("hello_world.json"), but routing doesn't work for this route and "/" always matches and is rendered.

**Comment by raphaelbauer** [comment]
Thanks for the clean report!

After having a look into the src it is obvious why it does not work: the getReverseRoute() does not add any context. It just bases the reversed route on the routing file.

We should do the following:
1) If available add context to prefix of generated route (From Context.String getContextPath())
2) (Optional possibly) If available add NinjaConstant.serverName so that we get the user facing server name
3) (Bonus) Add new method as companion to getReverseRoute(...) that does not take a Map, but an array of Objects, that will then be converted internally into the Map. This'd facilitate using the router inside templates (and without any not easy to use Maps)

**Comment by zoranzaric** [comment]
Where do I get the Context from in either my Router or ninja.RouterImpl?

I tried to inject the Context in my router but got:

java.lang.NullPointerException: Ninja injector cannot be generated. Please check log for further errors.
    at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:209) ~[guava-15.0.jar:na]
    at ninja.servlet.NinjaBootstap.boot(NinjaBootstap.java:90) ~[ninja-servlet-3.0.2.jar:na]
    at ninja.servlet.NinjaServletListener.getInjector(NinjaServletListener.java:75) ~[ninja-servlet-3.0.2.jar:na]
    at com.google.inject.servlet.GuiceServletContextListener.contextInitialized(GuiceServletContextListener.java:45) ~[guice-servlet-3.0.jar:na]
    at ninja.servlet.NinjaServletListener.contextInitialized(NinjaServletListener.java:50) ~[ninja-servlet-3.0.2.jar:na]
    at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:801) ~[jetty-server-9.1.2.v20140210.jar:9.1.2.v20140210]
    at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:446) ~[jetty-servlet-9.1.2.v20140210.jar:9.1.2.v20140210]
    at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:793) ~[jetty-server-9.1.2.v20140210.jar:9.1.2.v20140210]
    at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:296) ~[jetty-servlet-9.1.2.v20140210.jar:9.1.2.v20140210]
    at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:745) ~[jetty-server-9.1.2.v20140210.jar:9.1.2.v20140210]
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:69) ~[jetty-util-9.1.2.v20140210.jar:9.1.2.v20140210]
    at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:117) ~[jetty-util-9.1.2.v20140210.jar:9.1.2.v20140210]
    at org.eclipse.jetty.server.Server.start(Server.java:355) ~[jetty-server-9.1.2.v20140210.jar:9.1.2.v20140210]
    at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:99) ~[jetty-util-9.1.2.v20140210.jar:9.1.2.v20140210]
    at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:60) ~[jetty-server-9.1.2.v20140210.jar:9.1.2.v20140210]
    at org.eclipse.jetty.server.Server.doStart(Server.java:324) ~[jetty-server-9.1.2.v20140210.jar:9.1.2.v20140210]
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:69) ~[jetty-util-9.1.2.v20140210.jar:9.1.2.v20140210]
    at ninja.standalone.NinjaJetty.start(NinjaJetty.java:126) [ninja-standalone-3.0.2.jar:na]
    at ninja.standalone.NinjaJetty.main(NinjaJetty.java:52) [ninja-standalone-3.0.2.jar:na]

**Comment by raphaelbauer** [comment]
the context is not intended for injection. And will only be available when
you are inside e.g. your controller.

Have a look at the latest develop of Ninja. You should be able to access
the context via ninjaProperties.getContextPath()...

And NinjaProperties is something you can inject properly into the router :)
Then solving everything should be possibly without much hassle :)

Let me know if I can help!

Cheers,

Raphael

On Mon, Mar 3, 2014 at 3:27 PM, Zoran Zaric notifications@github.comwrote:

> Where do I get the Context from in either my Router or ninja.RouterImpl?
> 
> I tried to inject the Context in my router but got:
> 
> java.lang.NullPointerException: Ninja injector cannot be generated. Please
> check log for further errors.
> at
> com.google.common.base.Preconditions.checkNotNull(Preconditions.java:209)
> ~[guava-15.0.jar:na]
> at ninja.servlet.NinjaBootstap.boot(NinjaBootstap.java:90)
> ~[ninja-servlet-3.0.2.jar:na]
> at
> ninja.servlet.NinjaServletListener.getInjector(NinjaServletListener.java:75)
> ~[ninja-servlet-3.0.2.jar:na]
> at
> com.google.inject.servlet.GuiceServletContextListener.contextInitialized(GuiceServletContextListener.java:45)
> ~[guice-servlet-3.0.jar:na]
> at
> ninja.servlet.NinjaServletListener.contextInitialized(NinjaServletListener.java:50)
> ~[ninja-servlet-3.0.2.jar:na]
> at
> org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:801)
> ~[jetty-server-9.1.2.v20140210.jar:9.1.2.v20140210]
> at
> org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:446)
> ~[jetty-servlet-9.1.2.v20140210.jar:9.1.2.v20140210]
> at
> org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:793)
> ~[jetty-server-9.1.2.v20140210.jar:9.1.2.v20140210]
> at
> org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:296)
> ~[jetty-servlet-9.1.2.v20140210.jar:9.1.2.v20140210]
> at
> org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:745)
> ~[jetty-server-9.1.2.v20140210.jar:9.1.2.v20140210]
> at
> org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:69)
> ~[jetty-util-9.1.2.v20140210.jar:9.1.2.v20140210]
> at
> org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:117)
> ~[jetty-util-9.1.2.v20140210.jar:9.1.2.v20140210]
> at org.eclipse.jetty.server.Server.start(Server.java:355)
> ~[jetty-server-9.1.2.v20140210.jar:9.1.2.v20140210]
> at
> org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:99)
> ~[jetty-util-9.1.2.v20140210.jar:9.1.2.v20140210]
> at
> org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:60)
> ~[jetty-server-9.1.2.v20140210.jar:9.1.2.v20140210]
> at org.eclipse.jetty.server.Server.doStart(Server.java:324)
> ~[jetty-server-9.1.2.v20140210.jar:9.1.2.v20140210]
> at
> org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:69)
> ~[jetty-util-9.1.2.v20140210.jar:9.1.2.v20140210]
> at ninja.standalone.NinjaJetty.start(NinjaJetty.java:126)
> [ninja-standalone-3.0.2.jar:na]
> at ninja.standalone.NinjaJetty.main(NinjaJetty.java:52)
> [ninja-standalone-3.0.2.jar:na]
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ninjaframework/ninja/issues/151#issuecomment-36514228
> .

## 

inc: http://ars-machina.raphaelbauer.com
tech: http://ars-codia.raphaelbauer.com
web: http://raphaelbauer.com

**Comment by zoranzaric** [comment]
Is the latest snapshto (3.0.4-SNAPSHOT) build automatically?

**Comment by raphaelbauer** [comment]
you can build it locally... simply pull from github and then call "mvn
clean install" in ninja directory :)

On Mon, Mar 3, 2014 at 4:56 PM, Zoran Zaric notifications@github.comwrote:

> Is the latest snapshto (3.0.4-SNAPSHOT) build automatically?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ninjaframework/ninja/issues/151#issuecomment-36523795
> .

## 

inc: http://ars-machina.raphaelbauer.com
tech: http://ars-codia.raphaelbauer.com
web: http://raphaelbauer.com

**Comment by zoranzaric** [comment]
hm there's still a problem. When I deploy to a tomcat7 ninja.context is empty and I cant set it with tomcat's run configuration.

**Comment by raphaelbauer** [comment]
yes. there was something missing. should work by now. hmm... not really
nice to test though...

On Mon, Mar 3, 2014 at 7:47 PM, Zoran Zaric notifications@github.comwrote:

> hm there's still a problem. When I deploy to a tomcat7 ninja.context is
> empty and I cant set it with tomcat's run configuration.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ninjaframework/ninja/issues/151#issuecomment-36544247
> .

## 

inc: http://ars-machina.raphaelbauer.com
tech: http://ars-codia.raphaelbauer.com
web: http://raphaelbauer.com

**Comment by zoranzaric** [comment]
I tested it with my local tomcat and it still doesn't work.  Where is the context read from tomcat?

**Comment by raphaelbauer** [comment]
Forgot to push the change... Can you try to pull and try again? It works on
my local tomcat :)

**Comment by zoranzaric** [comment]
yay it works! thanks!

**Comment by raphaelbauer** [comment]
nice :)

On Mon, Mar 3, 2014 at 9:17 PM, Zoran Zaric notifications@github.comwrote:

> yay it works! thanks!
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ninjaframework/ninja/issues/151#issuecomment-36554206
> .

## 

inc: http://ars-machina.raphaelbauer.com
tech: http://ars-codia.raphaelbauer.com
web: http://raphaelbauer.com
