### ISSUE TITLE
When freemarker does not find template there is no proper error message rendered / just a white page

### ISSUE THREAD

**Issue by raphaelbauer** [ninjaframework/ninja#155]
6:50:57.913 [qtp1266405716-27] ERROR Ninja - Error processing Freemarker Template /views/ApplicationController/testGetContextPathWorks.ftl.html
java.io.FileNotFoundException: Template "/views/ApplicationController/testGetContextPathWorks.ftl.html" not found.
    at freemarker.template.Configuration.getTemplate(Configuration.java:742) ~[ninja-servlet-integration-test-3.0.4-SNAPSHOT-jar-with-dependencies.jar:na]
    at freemarker.template.Configuration.getTemplate(Configuration.java:665) ~[ninja-servlet-integration-test-3.0.4-SNAPSHOT-jar-with-dependencies.jar:na]
    at ninja.template.TemplateEngineFreemarker.invoke(TemplateEngineFreemarker.java:282) ~[ninja-servlet-integration-test-3.0.4-SNAPSHOT-jar-with-dependencies.jar:na]
    at ninja.utils.ResultHandler.renderWithTemplateEngineOrRaw(ResultHandler.java:111) [ninja-servlet-integration-test-3.0.4-SNAPSHOT-jar-with-dependencies.jar:na]
    at ninja.utils.ResultHandler.handleResult(ResultHandler.java:89) [ninja-servlet-integration-test-3.0.4-SNAPSHOT-jar-with-dependencies.jar:na]
    at ninja.NinjaImpl.invoke(NinjaImpl.java:114) [ninja-servlet-integration-test-3.0.4-SNAPSHOT-jar-with-dependencies.jar:na]
    at ninja.servlet.NinjaServletDispatcher.service(NinjaServletDispatcher.java:83) [ninja-servlet-integration-test-3.0.4-SNAPSHOT-jar-with-dependencies.jar:na]
    at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:263) [ninja-servlet-integration-test-3.0.4-SNAPSHOT-jar-with-dependencies.jar:na]
    at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:178) [ninja-servlet-integration-test-3.0.4-SNAPSHOT-jar-with-dependencies.jar:na]
    at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91) [ninja-servlet-integration-test-3.0.4-SNAPSHOT-jar-with-dependencies.jar:na]
    at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:62) [ninja-servlet-integration-test-3.0.4-SNAPSHOT-jar-with-dependencies.jar:na]
    at filters.DemoServletFilter.doFilter(DemoServletFilter.java:49) [ninja-servlet-integration-test-3.0.4-SNAPSHOT-jar-with-dependencies.jar:na]
    at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163) [ninja-servlet-integration-test-3.0.4-SNAPSHOT-jar-with-dependencies.jar:na]
    at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58) [ninja-servlet-integration-test-3.0.4-SNAPSHOT-jar-with-dependencies.jar:na]
    at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:118) [ninja-servlet-integration-test-3.0.4-SNAPSHOT-jar-with-dependencies.jar:na]
    at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:113) [ninja-servlet-integration-test-3.0.4-SNAPSHOT-jar-with-dependencies.jar:na]
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1615) [ninja-servlet-integration-test-3.0.4-SNAPSHOT-jar-with-dependencies.jar:na]
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:550) [ninja-servlet-integration-test-3.0.4-SNAPSHOT-jar-with-dependencies.jar:na]
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1112) [ninja-servlet-integration-test-3.0.4-SNAPSHOT-jar-with-dependencies.jar:na]
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:479) [ninja-servlet-integration-test-3.0.4-SNAPSHOT-jar-with-dependencies.jar:na]
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1046) [ninja-servlet-integration-test-3.0.4-SNAPSHOT-jar-with-dependencies.jar:na]
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [ninja-servlet-integration-test-3.0.4-SNAPSHOT-jar-with-dependencies.jar:na]
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [ninja-servlet-integration-test-3.0.4-SNAPSHOT-jar-with-dependencies.jar:na]
    at org.eclipse.jetty.server.Server.handle(Server.java:459) [ninja-servlet-integration-test-3.0.4-SNAPSHOT-jar-with-dependencies.jar:na]
    at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:281) [ninja-servlet-integration-test-3.0.4-SNAPSHOT-jar-with-dependencies.jar:na]
    at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:232) [ninja-servlet-integration-test-3.0.4-SNAPSHOT-jar-with-dependencies.jar:na]
    at org.eclipse.jetty.io.AbstractConnection$1.run(AbstractConnection.java:505) [ninja-servlet-integration-test-3.0.4-SNAPSHOT-jar-with-dependencies.jar:na]
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:607) [ninja-servlet-integration-test-3.0.4-SNAPSHOT-jar-with-dependencies.jar:na]
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:536) [ninja-servlet-integration-test-3.0.4-SNAPSHOT-jar-with-dependencies.jar:na]
    at java.lang.Thread.run(Thread.java:722) [na:1.7.0_13]

**Comment by raphaelbauer** [comment]
fixed in https://github.com/ninjaframework/ninja/commit/4571346261c33d6110639879902db81d875c02f0
