### ISSUE TITLE
JSON serialisation - jackson-databind/jackson-annotations versions

### ISSUE THREAD

**Issue by bihe** [ninjaframework/ninja#255]
Hi,

I got an error when creating a JSON respsonse with Results.json().render(object);
The object is rather simple, basic datatypes - nothing fancy.

> java.lang.nosuchmethoderror: com.fasterxml.jackson.databind.ser.beanpropertywriter.isunwrapping

The method is not present in the jackson-databind version supplied; had to explicitly change the version of
jackson-databind/jackson-annotations to 2.4.3 (as in jackson-core)

\Henrik

**Comment by raphaelbauer** [comment]
Can you provide more information - Complete stacktrace, Ninja version and source of the object you are trying to render and such.

It would be best if you could provide a demo project that allows to reproduce the error - this'd really help to fix the bug...

Thanks for the report!

**Comment by bihe** [comment]
Hello,

Sorry - **false alert** from my side. This is not a problem with ninjaframework, but with the _dependency I added_.

```
<!-- authentication with oauth -->
<dependency>
    <groupId>org.pac4j</groupId>
    <artifactId>pac4j-oauth</artifactId>
    <version>1.6.0</version>
</dependency>
```

This dependency adds the following maven resources:

```
jackson-databind-2.0.6
jackson-annotations-2.0.6
```

As a result I get the exception: 

[qtp2017354584-14] WARN  o.e.jetty.servlet.ServletHandler - Error for /hello_world.json
java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.ser.BeanPropertyWriter.isUnwrapping()Z
        at com.fasterxml.jackson.module.afterburner.ser.SerializerModifier.findProperties(SerializerModifier.java:90) ~[jackson-module-afterburner-2.4.3.jar:2.4.3]
        at com.fasterxml.jackson.module.afterburner.ser.SerializerModifier.changeProperties(SerializerModifier.java:49) ~[jackson-module-afterburner-2.4.3.jar:2.4.3]
        at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.constructBeanSerializer(BeanSerializerFactory.java:305) ~[jackson-databind-2.0.6.jar:na]
        at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.findBeanSerializer(BeanSerializerFactory.java:214) ~[jackson-databind-2.0.6.jar:na]
        at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.createSerializer(BeanSerializerFactory.java:182) ~[jackson-databind-2.0.6.jar:na]
        at com.fasterxml.jackson.databind.SerializerProvider._createUntypedSerializer(SerializerProvider.java:938) ~[jackson-databind-2.0.6.jar:na]
        at com.fasterxml.jackson.databind.SerializerProvider._createAndCacheUntypedSerializer(SerializerProvider.java:894) ~[jackson-databind-2.0.6.jar:na]
        at com.fasterxml.jackson.databind.SerializerProvider.findValueSerializer(SerializerProvider.java:429) ~[jackson-databind-2.0.6.jar:na]
        at com.fasterxml.jackson.databind.SerializerProvider.findTypedValueSerializer(SerializerProvider.java:520) ~[jackson-databind-2.0.6.jar:na]
        at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:87) ~[jackson-databind-2.0.6.jar:na]
        at com.fasterxml.jackson.databind.ObjectMapper._configAndWriteValue(ObjectMapper.java:2405) ~[jackson-databind-2.0.6.jar:na]
        at com.fasterxml.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:1948) ~[jackson-databind-2.0.6.jar:na]
        at ninja.template.TemplateEngineJson.invoke(TemplateEngineJson.java:54) ~[ninja-core-4.0.0.jar:na]
        at ninja.utils.ResultHandler.renderWithTemplateEngineOrRaw(ResultHandler.java:116) ~[ninja-core-4.0.0.jar:na]
        at ninja.utils.ResultHandler.handleResult(ResultHandler.java:78) ~[ninja-core-4.0.0.jar:na]
        at ninja.NinjaDefault.onRouteRequest(NinjaDefault.java:83) ~[ninja-core-4.0.0.jar:na]
        at ninja.servlet.NinjaServletDispatcher.service(NinjaServletDispatcher.java:86) ~[ninja-servlet-4.0.0.jar:na]
        at com.google.inject.servlet.ServletDefinition.doServiceImpl(ServletDefinition.java:279) ~[guice-servlet-4.0-beta5.jar:na]
        at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:269) ~[guice-servlet-4.0-beta5.jar:na]
        at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:180) ~[guice-servlet-4.0-beta5.jar:na]
        at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91) ~[guice-servlet-4.0-beta5.jar:na]
        at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:119) ~[guice-servlet-4.0-beta5.jar:na]
        at com.google.inject.servlet.GuiceFilter$1.call(GuiceFilter.java:133) ~[guice-servlet-4.0-beta5.jar:na]
        at com.google.inject.servlet.GuiceFilter$1.call(GuiceFilter.java:130) ~[guice-servlet-4.0-beta5.jar:na]
        at com.google.inject.servlet.GuiceFilter$Context.call(GuiceFilter.java:203) ~[guice-servlet-4.0-beta5.jar:na]
        at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:130) ~[guice-servlet-4.0-beta5.jar:na]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1650) ~[jetty-servlet-9.2.3.v20140905.jar:9.2.3.v20140905]
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:583) [jetty-servlet-9.2.3.v20140905.jar:9.2.3.v20140905]
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1125) [jetty-server-9.2.3.v20140905.jar:9.2.3.v20140905]
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515) [jetty-servlet-9.2.3.v20140905.jar:9.2.3.v20140905]
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1059) [jetty-server-9.2.3.v20140905.jar:9.2.3.v20140905]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [jetty-server-9.2.3.v20140905.jar:9.2.3.v20140905]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [jetty-server-9.2.3.v20140905.jar:9.2.3.v20140905]
        at org.eclipse.jetty.server.Server.handle(Server.java:497) [jetty-server-9.2.3.v20140905.jar:9.2.3.v20140905]
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311) [jetty-server-9.2.3.v20140905.jar:9.2.3.v20140905]
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:248) [jetty-server-9.2.3.v20140905.jar:9.2.3.v20140905]
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540) [jetty-io-9.2.3.v20140905.jar:9.2.3.v20140905]
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:610) [jetty-util-9.2.3.v20140905.jar:9.2.3.v20140905]
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:539) [jetty-util-9.2.3.v20140905.jar:9.2.3.v20140905]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_25]

When I remove the dependency or specify the "right" jackson version

```
jackson-databind-2.4.3
jackson-annotations-2.4.3
```

I get the expected result from ninja:

```
{
     content: "Hello World! Hello Json!"
}
```

**Comment by raphaelbauer** [comment]
Thanks for the explanation! Cheers :)
