### ISSUE TITLE
Filter with AuthenticityFilter fails on POST with enctype multipart/form-data (file upload)

### ISSUE THREAD

**Issue by emont01** [ninjaframework/ninja#394]
Hello,
I suppose this could be just a misunderstanding but I have a problem using the authenticity token with upload forms; I think the implementation of AuthenticityFilter needs to be changed.

Looking at the documentation [here](http://www.ninjaframework.org/documentation/basic_concepts/filters.html) and [here](http://www.ninjaframework.org/documentation/html_templating/advanced_topics.html) I understand that the following steps are required in order to the **authenticity token for protection against CSRF-requests** to work properly:
1. configure a route:
   
   ``` java
   public class Routes implements ApplicationRoutes {
   
       @Override
       public void init(Router router) {
           router.GET().route("/upload").with(UploadController.class, "showForm");
           router.POST().route("/upload").with(UploadController.class, "store");
       }
   
   }
   ```
2. implement my upload controller
   
   ``` java
   public class UploadController {
   
       @Inject
       org.slf4j.Logger logger;
   
       public Result showForm()
       {
           return Results.html();
       }
   
       @FilterWith({AuthenticityFilter.class})
       public Result store(Context context) throws Exception {
           // Make sure the context really is a multipart context...
           if (context.isMultipart()) {
   
               // This is the iterator we can use to iterate over the
               // contents of the request.
               FileItemIterator fileItemIterator = context.getFileItemIterator();
   
               while (fileItemIterator.hasNext()) {
                   FileItemStream item = fileItemIterator.next();
                   if (item.isFormField()) {
                       logger.debug("We don't care about form fields here"):
                   } else {
                       File uploadsDir = new File("/tmp/uploads");
                       uploadsDir.mkdirs(); //just to make sure the folders exists
                       File uploadedFile = new File(uploadsDir, 'test-file');
                       long bytesWritter = Files.copy(item.openStream(), uploadedFile.toPath(), java.nio.file.StandardCopyOption.REPLACE_EXISTING);
                       logger.debug(String.format("File [%s] uploaded to [%s]", item.getFieldName(), uploadedFile.getPath());
                   }
               }
           }
       }
   }
   ```
3. and finally add the authenticity token to my form
   
   ``` html
   <form method="POST" enctype="multipart/form-data" target='${reverseRoute("controllers.UploadController", "store")}'>
       <@authenticityForm/>
       <label>File upload
           <input type="file" id="upload" name="upload"/>
       </label>
       <button type="submit" >Submit</button>
   </form>
   ```

However every time I click submit, all I am getting a "401 Unauthorized error", so I decided to check the validation creating my own filter to check all sent parameters, that let me to discover that **context.getParameters()** returns an empty Map, however the authenticity token is present in the submitted form, and you can get it using a [FileItemIterator](http://www.ninjaframework.org/documentation/uploading_files.html) instance; here is the code of my custom filter:

``` java
package http.filters;

import java.io.IOException;
import java.io.StringWriter;
import java.util.stream.Collectors;
import javax.inject.Inject;
import ninja.Context;
import ninja.Filter;
import ninja.FilterChain;
import ninja.Result;
import ninja.utils.NinjaConstant;
import org.apache.commons.fileupload.FileItemIterator;
import org.apache.commons.fileupload.FileItemStream;
import org.apache.commons.fileupload.FileUploadException;
import org.apache.commons.io.IOUtils;
import org.slf4j.Logger;

/**
 *
 * @author Eivar Montenegro
 */

public class DummyFilter implements Filter
{
    @Inject
    private Logger logger;

    @Override
    public Result filter(FilterChain chain, Context context)
    {
        String authenticityToken = "";
        FileItemIterator iterator = context.getFileItemIterator();
        try {
            while (iterator.hasNext()) {
                FileItemStream item = iterator.next();
                if (item.isFormField() && item.getFieldName().equals(NinjaConstant.AUTHENTICITY_TOKEN)) {
                    StringWriter stringWriter = new StringWriter();
                    IOUtils.copy(item.openStream(), stringWriter);
                    authenticityToken = stringWriter.toString();
                    break;
                }
            }
        } catch (IOException | FileUploadException ex) {
            logger.error("Unable to get the field value: " + NinjaConstant.AUTHENTICITY_TOKEN, ex);
        }
        throw new RuntimeException(
                "context.getParameters: [" +
                context.getParameters().keySet().stream()
                .map(key -> {
                    return key + "=>" + context.getParameter(key);
                })
                .collect(Collectors.joining(", ")) + "] -------------------- \n FileItemStream: [" + authenticityToken + "]"
        );
    }
}
```

And the following is the error message generated by my filter, please notice that context.getParameters returns an empty Map:

```
java.lang.RuntimeException: context.getParameters: [] -------------------- 
 FileItemStream: [aac95a81-db06-4bb4-aabe-3b5a3c21a96d]
    at http.filters.DummyFilter.filter(DummyFilter.java:57)
    at ninja.FilterChainImpl.next(FilterChainImpl.java:35)
    at http.filters.AuthenticationFilter.filter(AuthenticationFilter.java:44)
    at ninja.FilterChainImpl.next(FilterChainImpl.java:35)
    at ninja.NinjaDefault.onRouteRequest(NinjaDefault.java:100)
```

**Comment by momiji** [comment]
Hello, unfortunately, this is an issue that can't be corrected easily.

As you've noticed, the AuthenticityFilter does not work with multipart form post, as it does use the existing FileItemIterator to read the autenticity token. You may believe that one might change the AuthenticityFilter and use the FileItemIterator in that case, but this is not as simple, because multipart form post are not just like usual get and post: data are read as streams, meaning once you read it you can't read it again.

There are two ways for handling your case:
- manually check the authenticity token by yourself in your code, instead of skiping form fields, and remove the AuthencityFilter from your controller
- or wait for PR #383, in 1 or 2, maybe 3 months, that changes the way multipart forms are handled, and you'll have to use the new way to handle uploaded files, and not the old one, because the AuthenticityFilter will force the switch to the new way...

The first should look like this:

``` java
    if (item.isFormField() && NinjaConstant.AUTHENTICITY_TOKEN.equals(item.getFieldName())) {
        String authenticityToken = Streams.asString(item.openStream());
        if (!context.getSession().getAuthenticityToken().equals(authenticityToken)) {
            return ninjaDefault.getForbiddenResult(context);
        }
    } else {
        ...
    }
```

**Comment by emont01** [comment]
Hello momiji,
I see! indeed it seems like a difficult problem, I am going to use option number 1 for now.
About reading an InputStream multiple times, maybe something like the [following](http://www.java-tutorial.ch/core-java-tutorial/reading-an-inputstream-multiple-times) can be used:  

``` java
import java.io.IOException;
import java.io.InputStream;
public class ResetOnCloseInputStream extends InputStream {
    private final InputStream decorated;
    public ResetOnCloseInputStream(InputStream inputStream) {
        if (!inputStream.markSupported()) {
            throw new IllegalArgumentException("marking not supported");
        }
        inputStream.mark( 1 << 32);
        decorated = inputStream;
    }
    @Override
    public void close() throws IOException {
        decorated.reset();
    }
    @Override
    public int read() throws IOException {
        return decorated.read();
    }
}
```

**Comment by emont01** [comment]
Please see https://github.com/ninjaframework/ninja/pull/383
