### ISSUE TITLE
Error occurred when execute command mvn eclipse:eclipse

### ISSUE THREAD

**Issue by chenghj11** [ninjaframework/ninja#530]
##Hello, thank you for the exciting work.

I want to execute mvn eclipse:eclipse command to build Ninja as an Eclipse project, and then develope my own project in Eclipse, but I get the error flowing:

`[INFO] ninja .............................................. SUCCESS [  1.108 s]
[INFO] ninja-core ......................................... SUCCESS [  3.073 s]
[INFO] ninja-metrics ...................................... SUCCESS [  2.046 s]
[INFO] ninja-metrics-graphite ............................. SUCCESS [  1.350 s]
[INFO] ninja-metrics-ganglia .............................. SUCCESS [  0.322 s]
[INFO] ninja-metrics-librato .............................. SUCCESS [  0.294 s]
[INFO] ninja-metrics-influxdb ............................. SUCCESS [  0.204 s]
[INFO] ninja-servlet ...................................... SUCCESS [  0.214 s]
[INFO] ninja-standalone ................................... SUCCESS [  0.440 s]
[INFO] ninja-test-utilities ............................... SUCCESS [  1.791 s]
[INFO] ninja-jaxy-routes .................................. SUCCESS [  2.441 s]
[INFO] ninja-maven-plugin ................................. FAILURE [  0.625 s]
[INFO] ninja-servlet-integration-test ..................... SKIPPED
[INFO] ninja-servlet-jpa-blog-integration-test ............ SKIPPED
[INFO] ninja-servlet-jpa-blog-archetype ................... SKIPPED
[INFO] ninja-servlet-archetype-simple ..................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 16.108 s
[INFO] Finished at: 2016-10-24T18:40:05+08:00
[INFO] Final Memory: 23M/56M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project ninja-maven-plugin: Could not resolve dependencies for project org.ninjaframework:ninja-maven-plugin:maven-plugin:6.0.0-SNAPSHOT: The following artifacts could not be resolved: org.ninjaframework:ninja-standalone:jar:6.0.0-SNAPSHOT, org.ninjaframework:ninja-servlet:jar:6.0.0-SNAPSHOT, org.ninjaframework:ninja-core:jar:6.0.0-SNAPSHOT: Could not find artifact org.ninjaframework:ninja-standalone:jar:6.0.0-SNAPSHOT -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project ninja-maven-plugin: Could not resolve dependencies for project org.ninjaframework:ninja-maven-plugin:maven-plugin:6.0.0-SNAPSHOT: The following artifacts could not be resolved: org.ninjaframework:ninja-standalone:jar:6.0.0-SNAPSHOT, org.ninjaframework:ninja-servlet:jar:6.0.0-SNAPSHOT, org.ninjaframework:ninja-core:jar:6.0.0-SNAPSHOT: Could not find artifact org.ninjaframework:ninja-standalone:jar:6.0.0-SNAPSHOT
    at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:221)
    at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.resolveProjectDependencies(LifecycleDependencyResolver.java:127)
    at org.apache.maven.lifecycle.internal.MojoExecutor.ensureDependenciesAreResolved(MojoExecutor.java:245)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:199)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
    at org.apache.maven.lifecycle.internal.MojoExecutor.executeForkedExecutions(MojoExecutor.java:352)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:197)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
    at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
    at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.project.DependencyResolutionException: Could not resolve dependencies for project org.ninjaframework:ninja-maven-plugin:maven-plugin:6.0.0-SNAPSHOT: The following artifacts could not be resolved: org.ninjaframework:ninja-standalone:jar:6.0.0-SNAPSHOT, org.ninjaframework:ninja-servlet:jar:6.0.0-SNAPSHOT, org.ninjaframework:ninja-core:jar:6.0.0-SNAPSHOT: Could not find artifact org.ninjaframework:ninja-standalone:jar:6.0.0-SNAPSHOT
    at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:211)
    at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:195)
    ... 27 more
Caused by: org.eclipse.aether.resolution.DependencyResolutionException: The following artifacts could not be resolved: org.ninjaframework:ninja-standalone:jar:6.0.0-SNAPSHOT, org.ninjaframework:ninja-servlet:jar:6.0.0-SNAPSHOT, org.ninjaframework:ninja-core:jar:6.0.0-SNAPSHOT: Could not find artifact org.ninjaframework:ninja-standalone:jar:6.0.0-SNAPSHOT
    at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:384)
    at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:205)
    ... 28 more
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: The following artifacts could not be resolved: org.ninjaframework:ninja-standalone:jar:6.0.0-SNAPSHOT, org.ninjaframework:ninja-servlet:jar:6.0.0-SNAPSHOT, org.ninjaframework:ninja-core:jar:6.0.0-SNAPSHOT: Could not find artifact org.ninjaframework:ninja-standalone:jar:6.0.0-SNAPSHOT
    at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:444)
    at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246)
    at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:367)
    ... 29 more
Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact org.ninjaframework:ninja-standalone:jar:6.0.0-SNAPSHOT
    at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:434)
    ... 31 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :ninja-maven-plugin
`

Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-11T00:41:47+08:00)
Maven home: /opt/maven
Java version: 1.8.0_45, vendor: Oracle Corporation
Java home: /opt/jdk1.8.0_45/jre
Default locale: zh_CN, platform encoding: UTF-8
OS name: "linux", version: "2.6.32-573.7.1.el6.x86_64", arch: "amd64", family: "unix"

![image](https://cloud.githubusercontent.com/assets/1947030/19646390/ccdf7454-9a2b-11e6-97e2-9aadf33f4cfe.png)

**Comment by jlannoy** [comment]
You don't need to run eclipse:eclipse to have the project work in your Eclipse IDE. Simply use "Import project as a Maven project..." and select the ninja base directory.
