### ISSUE TITLE
javax.crypto.BadPaddingException when switching between instances

### ISSUE THREAD

**Issue by jjlauer** [ninjaframework/ninja#532]
When switching between instances (e.g. same app but configured w/ different cookie encryption keys), we are sometimes getting 500 errors rather than the expected cleaning of the Ninja session.

Example session cookie: 28afa10d7322bc2afe741755b194f92d2cbcd935-7tu7louhOSy9K78MxpbcCjzZzqkgLCt-c-zbzYZ9oo3HIKpvl0Q-5CarMlGX2NenFHQvixZyDsrLwF-ZZIVzqhVyD8aGl0DsXMN_iIwStyM

Error

```
java.lang.RuntimeException: javax.crypto.BadPaddingException: Given final block not properly padded
	at ninja.utils.CookieEncryption.decrypt(CookieEncryption.java:139) ~[org.ninjaframework.ninja-core-5.8.0.jar:na]
	at ninja.session.SessionImpl.init(SessionImpl.java:117) ~[org.ninjaframework.ninja-core-5.8.0.jar:na]
	at ninja.utils.AbstractContext.init(AbstractContext.java:95) ~[org.ninjaframework.ninja-core-5.8.0.jar:na]
	at ninja.undertow.NinjaUndertowContext.init(NinjaUndertowContext.java:110) ~[com.fizzed.ninja-undertow-5.7.0.undertow2.jar:5.7.0.undertow2]
	at ninja.undertow.NinjaUndertowHandler.handleRequest(NinjaUndertowHandler.java:53) ~[com.fizzed.ninja-undertow-5.7.0.undertow2.jar:5.7.0.undertow2]
	at io.undertow.server.handlers.form.EagerFormParsingHandler.handleRequest(EagerFormParsingHandler.java:55) ~[io.undertow.undertow-core-1.4.0.Final.jar:1.4.0.Final]
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:202) ~[io.undertow.undertow-core-1.4.0.Final.jar:1.4.0.Final]
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:805) ~[io.undertow.undertow-core-1.4.0.Final.jar:1.4.0.Final]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_102]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_102]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_102]
Caused by: javax.crypto.BadPaddingException: Given final block not properly padded
	at com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:975) ~[sunjce_provider.jar:1.8.0_101]
	at com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:833) ~[sunjce_provider.jar:1.8.0_101]
	at com.sun.crypto.provider.AESCipher.engineDoFinal(AESCipher.java:446) ~[sunjce_provider.jar:1.8.0_101]
	at javax.crypto.Cipher.doFinal(Cipher.java:2165) ~[na:1.8.0_102]
	at ninja.utils.CookieEncryption.decrypt(CookieEncryption.java:129) ~[org.ninjaframework.ninja-core-5.8.0.jar:na]
	... 10 common frames omitted
```

**Comment by raphaelbauer** [comment]
Strange. Stupid question: Do you have any ideas where this might come from?

**Comment by jjlauer** [comment]
Not sure exactly.  I think `javax.crypto.BadPaddingException` just needs to be caught and treated as an invalid cookie and simply cleaned vs. trigger an 500 error.

**Comment by raphaelbauer** [comment]
I am just wondering wether that happens always or just pops up and then is gone... Or in other terms: Is there a way to reproduce that "error" reliably so we can write a test against it?

**Comment by jjlauer** [comment]
Alright, figured it out.  One machine had the Java crypto extensions installed -- thus had 256-bit encryption enabled.  The other machine didn't and had 128-bit instead.

Perhaps some enforcement of the the encryption-level at boot would be helpful.

**Comment by jjlauer** [comment]
In order to force sessions to be cleared in this specific case, just change the cookie encryption key to something else.  Then all user sessions will be cleared automatically vs. continual 500 server errors.

**Comment by raphaelbauer** [comment]
Should we add a more meaningful log message in case someone else gets those errors?

**Comment by jjlauer** [comment]
A log.warn + clearing the session may be good.
