### ISSUE TITLE
JPA bug with blob called twice > Connection.close() has already been called

### ISSUE THREAD

**Issue by danielsawan** [ninjaframework/ninja#556]
Hello !

I have a strange problem with hibernate JPA. I have a model class containing a blob :

```java
@Entity
@Table(name = "simple_blob")
public class SimpleBlob {
	
	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	public Long id;
	
	@Lob
	public byte[] data;
	
	public Long getId() {
		return id;
	}
	public void setId(Long id) {
		this.id = id;
	}
	public byte[] getData() {
		return data;
	}
	public void setData(byte[] data) {
		this.data = data;
	}
}
```

And my Dao contains :

```java

    	EntityManager entityManager = entityManagerProvider.get();
    	
    	entityManager.find(SimpleBlob.class, 2442l); 
    	entityManager.find(SimpleBlob.class, 2443l); // crash here
    	
```

The error is :

```java
21:17:44.858 [DefaultQuartzScheduler_Worker-1] WARN  o.h.e.jdbc.spi.SqlExceptionHelper - SQL Error: 0, SQLState: 08S01
21:17:44.858 [DefaultQuartzScheduler_Worker-1] ERROR o.h.e.jdbc.spi.SqlExceptionHelper - Communications link failure

Last packet sent to the server was 0 ms ago.
21:17:44.859 [DefaultQuartzScheduler_Worker-1] INFO  o.h.e.i.DefaultLoadEventListener - HHH000327: Error performing load command : org.hibernate.exception.JDBCConnectionException: could not extract ResultSet
21:17:44.860 [DefaultQuartzScheduler_Worker-1] WARN  c.m.v2.c3p0.impl.NewPooledConnection - [c3p0] A PooledConnection that has already signalled a Connection error is still in use!
21:17:44.864 [DefaultQuartzScheduler_Worker-1] WARN  c.m.v2.c3p0.impl.NewPooledConnection - [c3p0] Another error has occurred [ com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Connection.close() has already been called. Invalid operation in this state. ] which will not be reported to listeners!
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Connection.close() has already been called. Invalid operation in this state.
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.7.0_45]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57) ~[na:1.7.0_45]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.7.0_45]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526) ~[na:1.7.0_45]
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:406) ~[mysql-connector-java-5.1.6.jar:na]
        at com.mysql.jdbc.Util.getInstance(Util.java:381) ~[mysql-connector-java-5.1.6.jar:na]
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:984) ~[mysql-connector-java-5.1.6.jar:na]
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956) ~[mysql-connector-java-5.1.6.jar:na]
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:926) ~[mysql-connector-java-5.1.6.jar:na]
        at com.mysql.jdbc.ConnectionImpl.getMutex(ConnectionImpl.java:3018) ~[mysql-connector-java-5.1.6.jar:na]
        at com.mysql.jdbc.ConnectionImpl.rollback(ConnectionImpl.java:4564) ~[mysql-connector-java-5.1.6.jar:na]
        at com.mchange.v2.c3p0.impl.NewProxyConnection.rollback(NewProxyConnection.java:860) ~[c3p0-0.9.2.1.jar:0.9.2.1]
        at org.hibernate.engine.transaction.internal.jdbc.JdbcTransaction.doRollback(JdbcTransaction.java:163) [hibernate-core-4.3.8.Final.jar:4.3.8.Final]
        at org.hibernate.engine.transaction.spi.AbstractTransactionImpl.rollback(AbstractTransactionImpl.java:211) [hibernate-core-4.3.8.Final.jar:4.3.8.Final]
        at org.hibernate.jpa.internal.TransactionImpl.rollback(TransactionImpl.java:108) [hibernate-entitymanager-4.3.8.Final.jar:4.3.8.Final]
        at com.google.inject.persist.jpa.JpaLocalTxnInterceptor.rollbackIfNecessary(JpaLocalTxnInterceptor.java:153) [guice-persist-4.0.jar:na]
        at com.google.inject.persist.jpa.JpaLocalTxnInterceptor.invoke(JpaLocalTxnInterceptor.java:74) [guice-persist-4.0.jar:na]
        at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:75) [guice-4.0.jar:na]
        at com.google.inject.internal.InterceptorStackCallback.intercept(InterceptorStackCallback.java:55) [guice-4.0.jar:na]

```

And if i change my Dao code to :

```java

    	EntityManager entityManager = entityManagerProvider.get();
    	
    	entityManager.find(User.class, 1l);
    	entityManager.find(User.class, 2l);
    	
```

this work perfectly. 

It seems like the bug only happen with Blob access and only on the second call. Any idea of what is happening ?

**Comment by danielsawan** [comment]
i finally found. The problem was a param in my jdbc connection : useCompression=true

`%dev.db.connection.url=jdbc:mysql://myhost/mydb?characterEncoding=UTF-8&useCompression=true`

Just turn this to false or remove it solve the problem.

**Comment by raphaelbauer** [comment]
Thanks for the feedback!
