### ISSUE TITLE
Routes w/ no path params trigger NPE if ninja.Route.getPathParametersEncoded called

### ISSUE THREAD

**Issue by jjlauer** [ninjaframework/ninja#565]
Looks like the routing changes for latest Ninja break something that used to work.

A route like this used to work:

```java
router.GET().route("/robots.txt").with(AssetsController::serveStatic);
```

With Ninja 6 an NPE is triggered:

```
java.lang.NullPointerException: null
	at ninja.Route.getPathParametersEncoded(Route.java:128) ~[ninja-core-6.0.0-beta2.jar:na]
	at ninja.utils.AbstractContext.getPathParameter(AbstractContext.java:189) ~[ninja-core-6.0.0-beta2.jar:na]
	at ninja.AssetsController.getFileNameFromPathOrReturnRequestPath(AssetsController.java:225) ~[ninja-core-6.0.0-beta2.jar:na]
	at ninja.AssetsController.access$000(AssetsController.java:45) ~[ninja-core-6.0.0-beta2.jar:na]
	at ninja.AssetsController$1.render(AssetsController.java:93) ~[ninja-core-6.0.0-beta2.jar:na]
	at ninja.utils.ResultHandler.handleRenderable(ResultHandler.java:87) ~[ninja-core-6.0.0-beta2.jar:na]
	at ninja.utils.ResultHandler.handleResult(ResultHandler.java:60) ~[ninja-core-6.0.0-beta2.jar:na]
	at ninja.NinjaDefault.onRouteRequest(NinjaDefault.java:104) ~[ninja-core-6.0.0-beta2.jar:na]
	at ninja.undertow.NinjaUndertowHandler.handleRequest(NinjaUndertowHandler.java:56) [ninja-undertow-6.0.0-undertow1.jar:6.0.0-undertow1]
	at io.undertow.server.handlers.form.EagerFormParsingHandler.handleRequest(EagerFormParsingHandler.java:55) [undertow-core-1.4.8.Final.jar:1.4.8.Final]
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:210) [undertow-core-1.4.8.Final.jar:1.4.8.Final]
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:809) [undertow-core-1.4.8.Final.jar:1.4.8.Final]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_102]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_102]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_102]
```

The fix is trivial in getPathParametersEncoded, but a unit test should be added using the robots.txt example to make sure we don't regress.

**Comment by raphaelbauer** [comment]
Is there a chance for a fix until the final Ninja 6 release?

**Comment by jjlauer** [comment]
I will try to get a fix submitted this week for it.

-Joe

**Comment by raphaelbauer** [comment]
👍

**Comment by jjlauer** [comment]
@raphaelbauer Submitted a fix for this. https://github.com/ninjaframework/ninja/pull/566

Hey, I added Greenback (my startup that's been funding all the work I do on Ninja) to the docs in this PR too.  Let me know if you have any issue w/ it and I can back it out.

**Comment by raphaelbauer** [comment]
More than ok. All the very best for Greenback.com! Thanks for the fix!

**Comment by jjlauer** [comment]
Fixed.
