### ISSUE TITLE
Unable to start NinjaJetty

### ISSUE THREAD

**Issue by AldeRoberge** [ninjaframework/ninja#602]
I get this error

`18:15:12.691 [NinjaJetty] ERROR ninja.standalone.NinjaJetty - Unable to start NinjaJetty
org.eclipse.jetty.util.MultiException: Multiple exceptions
	at org.eclipse.jetty.server.Server.doStart(Server.java:386) ~[jetty-server-9.3.15.v20161220.jar:9.3.15.v20161220]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) ~[jetty-util-9.3.15.v20161220.jar:9.3.15.v20161220]
	at ninja.standalone.NinjaJetty.doStart(NinjaJetty.java:167) ~[ninja-standalone-6.2.2.jar:na]
	at ninja.standalone.AbstractStandalone.start(AbstractStandalone.java:201) ~[ninja-core-6.2.2.jar:na]
	at ninja.standalone.AbstractStandalone.run(AbstractStandalone.java:98) ~[ninja-core-6.2.2.jar:na]
	at ninja.standalone.AutoStandalone.main(AutoStandalone.java:34) [ninja-core-6.2.2.jar:na]
	Suppressed: java.net.BindException: Address already in use: bind
		at sun.nio.ch.Net.bind0(Native Method) ~[na:1.8.0_121]
		at sun.nio.ch.Net.bind(Net.java:433) ~[na:1.8.0_121]
		at sun.nio.ch.Net.bind(Net.java:425) ~[na:1.8.0_121]
		at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223) ~[na:1.8.0_121]
		at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74) ~[na:1.8.0_121]
		at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:317) ~[jetty-server-9.3.15.v20161220.jar:9.3.15.v20161220]
		at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80) ~[jetty-server-9.3.15.v20161220.jar:9.3.15.v20161220]
		at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:235) ~[jetty-server-9.3.15.v20161220.jar:9.3.15.v20161220]
		at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) ~[jetty-util-9.3.15.v20161220.jar:9.3.15.v20161220]
		at org.eclipse.jetty.server.Server.doStart(Server.java:401) ~[jetty-server-9.3.15.v20161220.jar:9.3.15.v20161220]
		... 5 common frames omitted
Caused by: java.net.BindException: Address already in use: bind
	at sun.nio.ch.Net.bind0(Native Method) ~[na:1.8.0_121]
	at sun.nio.ch.Net.bind(Net.java:433) ~[na:1.8.0_121]
	at sun.nio.ch.Net.bind(Net.java:425) ~[na:1.8.0_121]
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223) ~[na:1.8.0_121]
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74) ~[na:1.8.0_121]
	at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:317) ~[jetty-server-9.3.15.v20161220.jar:9.3.15.v20161220]
	at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80) ~[jetty-server-9.3.15.v20161220.jar:9.3.15.v20161220]
	at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:235) ~[jetty-server-9.3.15.v20161220.jar:9.3.15.v20161220]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) ~[jetty-util-9.3.15.v20161220.jar:9.3.15.v20161220]
	at org.eclipse.jetty.server.Server.doStart(Server.java:401) ~[jetty-server-9.3.15.v20161220.jar:9.3.15.v20161220]
	... 5 common frames omitted
[ERROR] JVM process for Standalone terminated (next file change will attempt to restart it)`

How do I restart NinjaJetty?

**Comment by AldeRoberge** [comment]
I have been restarting my computer when it does that but there must be a better way to close Ninja properly and lunch it again?

**Comment by AldeRoberge** [comment]
How do I restart ninja.standalone.NinjaJetty

**Comment by jjlauer** [comment]
Alde,

Happy to help, but you'd to include more info about your environment is
(e.g. operating system) and what exactly you're doing.  For example, are
you running this on the command line?  If so what are you typing.

If I assume you mean you're running it in development mode from the command
like via something like "mvn ninja:run" then hitting CTRL-C will cause
Ninja to stop running.  The error you included indicates something is
running on the same port you're trying to run it on.  Instead of restarting
your computer, you can just simply kill the process that's running the JVM
that hosts Ninja.  If CTRL-C isn't causing Ninja to exit, that could be
environment/shell related, or application specific (e.g. you have threads
not exiting, etc.).

-Joe

**Comment by AldeRoberge** [comment]
Hello Joe, thanks so much for the helpful answer.

I run Ninja from Eclipse (Run configurations -> Maven goals : **ninja:run**)
And I closed it by accident this time by hitting the red square (**Terminate**)

So I'm not sure CTRL+C will still work.

But next time, I'll kill javaw.exe and hopefully it works.

**Comment by AldeRoberge** [comment]
This error happens when there is already an instance of Ninja Jetty running. To close ninja-jetty, open Task Manager and kill the process 'java.exe'.

**Comment by liudianpeng** [comment]
@jjlauer 

$ mvn ninja:run
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building ninja69demo 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- ninja-maven-plugin:6.9.0:run (default-cli) @ ninja69demo ---
[INFO] ------------------------------------------------------------------------
[INFO] Ninja will watch dirs:
[INFO]  D:\home\ninja69demo\target\classes
[INFO]
[INFO] Ninja will launch with:
[INFO]       context: <default>
[INFO]          mode: dev
[INFO]          port: <default>
[INFO]      ssl port: <default>
[INFO]     mainClass: ninja.standalone.AutoStandalone
[INFO] extra jvmArgs: <none>
[INFO] ------------------------------------------------------------------------
10:31:39.367 [main] INFO  ninja.utils.NinjaModeHelper - Ninja is running in mode dev
10:31:39.632 [NinjaJetty] INFO  org.eclipse.jetty.util.log - Logging initialized @918ms to org.eclipse.jetty.util.log.Slf4jLog
10:31:39.741 [NinjaJetty] ERROR ninja.standalone.NinjaJetty - Unable to configure NinjaJetty
java.io.IOException: Invalid keystore format
        at sun.security.provider.JavaKeyStore.engineLoad(Unknown Source)
        at sun.security.provider.JavaKeyStore$JKS.engineLoad(Unknown Source)
        at java.security.KeyStore.load(Unknown Source)
        at ninja.standalone.StandaloneHelper.loadKeyStore(StandaloneHelper.java:170)
        at ninja.standalone.StandaloneHelper.createSSLContext(StandaloneHelper.java:180)
        at ninja.standalone.AbstractStandalone.createSSLContext(AbstractStandalone.java:396)
        at ninja.standalone.NinjaJetty.doConfigure(NinjaJetty.java:123)
        at ninja.standalone.AbstractConsole.configure(AbstractConsole.java:76)
        at ninja.standalone.AbstractStandalone.run(AbstractStandalone.java:106)
        at ninja.standalone.AutoStandalone.main(AutoStandalone.java:34)
[ERROR] JVM process for Standalone terminated (next file change will attempt to restart it)
