### ISSUE TITLE
Error when annotating controller method with multiple metrics annotations

### ISSUE THREAD

**Issue by xgp** [ninjaframework/ninja#610]
I set up the metrics module as described here: http://www.ninjaframework.org/documentation/basic_concepts/metrics.html

I want to time and meter a controller method:

```
@Metered @Timed
public Result index() {
    ...
}
```

I get the following exception when I run it:

```
java.lang.IllegalArgumentException: controllers.ApplicationController.index is already used for a different type of metric
	at com.codahale.metrics.MetricRegistry.getOrAdd(MetricRegistry.java:321) ~[metrics-core-3.1.0.jar:3.1.0]
	at com.codahale.metrics.MetricRegistry.meter(MetricRegistry.java:134) ~[metrics-core-3.1.0.jar:3.1.0]
	at ninja.metrics.MeteredInterceptor.invoke(MeteredInterceptor.java:47) ~[ninja-metrics-6.2.2.jar:na]
	at ninja.metrics.TimedInterceptor.invoke(TimedInterceptor.java:57) ~[ninja-metrics-6.2.2.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_162]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_162]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_162]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_162]
	at ninja.params.ControllerMethodInvoker.invoke(ControllerMethodInvoker.java:76) ~[ninja-core-6.2.2.jar:na]
	at ninja.FilterChainEnd.next(FilterChainEnd.java:45) ~[ninja-core-6.2.2.jar:na]
	at ninja.metrics.InstrumentedNinja.onRouteRequest(InstrumentedNinja.java:84) ~[ninja-metrics-6.2.2.jar:na]
	at ninja.metrics.TimedInterceptor.invoke(TimedInterceptor.java:57) ~[ninja-metrics-6.2.2.jar:na]
	at ninja.servlet.NinjaServletDispatcher.service(NinjaServletDispatcher.java:86) [ninja-servlet-6.2.2.jar:na]
	at com.google.inject.servlet.ServletDefinition.doServiceImpl(ServletDefinition.java:286) [guice-servlet-4.1.0.jar:na]
	at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:276) [guice-servlet-4.1.0.jar:na]
	at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:181) [guice-servlet-4.1.0.jar:na]
	at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91) [guice-servlet-4.1.0.jar:na]
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:85) [guice-servlet-4.1.0.jar:na]
	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:120) [guice-servlet-4.1.0.jar:na]
	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:135) [guice-servlet-4.1.0.jar:na]
	at ninja.servlet.NinjaServletFilter.doFilter(NinjaServletFilter.java:106) [ninja-servlet-6.2.2.jar:na]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759) [jetty-servlet-9.3.15.v20161220.jar:9.3.15.v20161220]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:582) [jetty-servlet-9.3.15.v20161220.jar:9.3.15.v20161220]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180) [jetty-server-9.3.15.v20161220.jar:9.3.15.v20161220]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:512) [jetty-servlet-9.3.15.v20161220.jar:9.3.15.v20161220]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112) [jetty-server-9.3.15.v20161220.jar:9.3.15.v20161220]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [jetty-server-9.3.15.v20161220.jar:9.3.15.v20161220]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134) [jetty-server-9.3.15.v20161220.jar:9.3.15.v20161220]
	at org.eclipse.jetty.server.Server.handle(Server.java:534) [jetty-server-9.3.15.v20161220.jar:9.3.15.v20161220]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320) [jetty-server-9.3.15.v20161220.jar:9.3.15.v20161220]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251) [jetty-server-9.3.15.v20161220.jar:9.3.15.v20161220]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:283) [jetty-io-9.3.15.v20161220.jar:9.3.15.v20161220]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110) [jetty-io-9.3.15.v20161220.jar:9.3.15.v20161220]
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93) [jetty-io-9.3.15.v20161220.jar:9.3.15.v20161220]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303) [jetty-util-9.3.15.v20161220.jar:9.3.15.v20161220]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148) [jetty-util-9.3.15.v20161220.jar:9.3.15.v20161220]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136) [jetty-util-9.3.15.v20161220.jar:9.3.15.v20161220]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671) [jetty-util-9.3.15.v20161220.jar:9.3.15.v20161220]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589) [jetty-util-9.3.15.v20161220.jar:9.3.15.v20161220]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_162]
```

This resolves when only using one annotation at a time. Is it a known problem, or is there a way to use multiple measurement annotations at the same time? Seems like a fix would be to use the metric type in the naming, but I don't know what else that might break.

**Comment by raphaelbauer** [comment]
Did you try to give it an explicit name like 

```
@Metered("ApplicationContorller.index.metered") 
@Timed("ApplicationContorller.index.timed") 
public Result index() {
    ...
}
```

**Comment by xgp** [comment]
Thank you. Giving it a name disambiguates it for the metrics lib.

I'm sure it would break how some people are already using it, but I'd suggest tacking on the metric type (e.g. metered, timed, counted) to the default name so multiple metrics interceptors could be used at the same time.

**Comment by raphaelbauer** [comment]
That sounds clever. We are open for PRs! Feel free to contribute that change :)
