### ISSUE TITLE
Can't create new instance of class javax.mail.Session

### ISSUE THREAD

**Issue by buefmaster** [ninjaframework/ninja#680]
Hello ninjas!

we have a stacktrace, which we cannot verify why this case is happening.

`12:46:12.743 [https-jsse-nio-443-exec-1] ERROR n.bodyparser.BodyParserEnginePost - Can't create new instance of class javax.mail.Session
java.lang.InstantiationException: javax.mail.Session
	at java.base/java.lang.Class.newInstance(Class.java:571)
	at ninja.bodyparser.BodyParserEnginePost.invoke(BodyParserEnginePost.java:66)
	at ninja.bodyparser.BodyParserEnginePost.invoke(BodyParserEnginePost.java:57)
	at ninja.utils.AbstractContext.parseBody(AbstractContext.java:280)
	at ninja.params.ArgumentExtractors$BodyAsExtractor.extract(ArgumentExtractors.java:456)
	at ninja.params.ControllerMethodInvoker.invoke(ControllerMethodInvoker.java:70)
	at ninja.FilterChainEnd.next(FilterChainEnd.java:45)
	at ninja.metrics.InstrumentedNinja.onRouteRequest(InstrumentedNinja.java:84)
	at conf.Ninja.onRouteRequest(Ninja.java:86)
	at ninja.servlet.NinjaServletDispatcher.service(NinjaServletDispatcher.java:86)
	at com.google.inject.servlet.ServletDefinition.doServiceImpl(ServletDefinition.java:290)
	at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:280)
	at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:184)
	at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:89)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:85)
	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:121)
	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:133)
	at ninja.servlet.NinjaServletFilter.doFilter(NinjaServletFilter.java:106)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:610)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:137)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:660)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:798)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NoSuchMethodException: javax.mail.Session.<init>()
	at java.base/java.lang.Class.getConstructor0(Class.java:3349)
	at java.base/java.lang.Class.newInstance(Class.java:556)
	... 36 common frames omitted`

This stacktrace is happening multiple times a day and is not sending out emails.

We are sending out E-Mails in cronjobs. For that we are using the default libaries.

application.conf:

`
smtp.host=smtp.strato.de
smtp.port=465
smtp.ssl=true
smtp.user=****
smtp.password=****
smtp.debug=false`

and this is an example code:

`	
    
@Inject
    Provider<Mail> mailProvider;

    @Inject
    Postoffice postoffice;
	
	@Schedule(delay = 3, initialDelay = 3, timeUnit = TimeUnit.MINUTES)
    public void sendOrderIsCurrentlyNotPayed() {
		Customer customer = getCustomerFromDatabase()
		Mail mail = mailProvider.get();

		mail.setSubject("Your order");
		mail.setFrom("no-reply@mydoimain.com");
		mail.setCharset("utf-8");

		mail.addTo(customer.getEmailadress());
		
		mail.setBodyHtml("<html>some stuff</html>");
		try {
			postoffice.send(mail);
		} catch (Exception e) {

		}
	`

I have no idea, why this stacktrace is happening. Can someone help us out?

**Comment by thibaultmeyer** [comment]
Hello @buefmaster,

I can't reproduce your bug. Can you give more information about your environment (Ninja version, Maven version, Java version, Operating System) and give a case to reproduce the bug? Are you using the right imports?



Here a working example tested on Ninja 6.8.2-SNAPSHOT with Java 8.
 
**pom.xml**
```xml
<dependency>
    <groupId>org.ninjaframework</groupId>
    <artifactId>ninja-postoffice</artifactId>
    <version>${ninja.version}</version>
</dependency>
```

**Module.java (register Postoffice module)**
```java
 install(new NinjaPostofficeModule());
```

**MailJob.class**
```java
import com.google.inject.Inject;
import com.google.inject.Provider;
import com.google.inject.Singleton;
import ninja.postoffice.Mail;
import ninja.postoffice.Postoffice;

@Singleton
public class MailJob {

    @Inject
    Provider<Mail> mailProvider;

    @Inject
    Postoffice postoffice;

    @Schedule(delay = 3000, initialDelay = 3, timeUnit = TimeUnit.SECONDS)
    public void sendOrderIsCurrentlyNotPayed() {
        final Mail mail = mailProvider.get();

        mail.setSubject("Test");
        mail.setFrom("no-reply@domain.local");
        mail.setCharset("UTF-8");

        mail.addTo("test@domain.local");

        mail.setBodyHtml("<html>some stuff</html>");
        try {
            postoffice.send(mail);
        } catch (Exception e) {
            e.printStackTrace();
        }
}
```


**Output (dev mode)**
```
07:45:28.668 [pool-1-thread-1] INFO  n.postoffice.mock.PostofficeMockImpl - --------------------------------------------------------
07:45:28.668 [pool-1-thread-1] INFO  n.postoffice.mock.PostofficeMockImpl - Mock mailer received send email request
07:45:28.668 [pool-1-thread-1] INFO  n.postoffice.mock.PostofficeMockImpl - --------------------------------------------------------
07:45:28.668 [pool-1-thread-1] INFO  n.postoffice.mock.PostofficeMockImpl - Subject : Your order
07:45:28.668 [pool-1-thread-1] INFO  n.postoffice.mock.PostofficeMockImpl - From    : no-reply@mydoimain.com
07:45:28.668 [pool-1-thread-1] INFO  n.postoffice.mock.PostofficeMockImpl - To      : test@domain.local
07:45:28.668 [pool-1-thread-1] INFO  n.postoffice.mock.PostofficeMockImpl - ----- Html content -------------------------------------
07:45:28.668 [pool-1-thread-1] INFO  n.postoffice.mock.PostofficeMockImpl - <html>some stuff</html>
07:45:28.668 [pool-1-thread-1] INFO  n.postoffice.mock.PostofficeMockImpl - ----- Text content -------------------------------------
07:45:28.668 [pool-1-thread-1] INFO  n.postoffice.mock.PostofficeMockImpl - null
07:45:28.669 [pool-1-thread-1] INFO  n.postoffice.mock.PostofficeMockImpl - --------------------------------------------------------
```

**Comment by buefmaster** [comment]
Hey, yeah I am sorry. Issue was at our side. We have inserted 2 filters-mappings in the file WEB-INF/web.xml, which started the instance 2 times in one instance. So we removed one and everything was looking good again. 

Sorry for not updating the issue.
