### ISSUE TITLE
NPE in Ninja when trying to render error message

### ISSUE THREAD

**Issue by asolntsev** [ninjaframework/ninja#715]
This exception happens in Ninja framework when controller returns null or throws an exception (I am not sure). 

```java
09:43:56.870 [qtp1830190936-14] WARN  o.e.j.s.HttpChannel [HttpChannel.java:677] /banklink/payment
java.lang.NullPointerException: null
at java.base/java.text.MessageFormat.applyPattern(MessageFormat.java:448)
at java.base/java.text.MessageFormat.<init>(MessageFormat.java:390)
at ninja.i18n.MessagesImpl.getMessageFormatForLocale(MessagesImpl.java:305)
at ninja.i18n.MessagesImpl.getWithDefault(MessagesImpl.java:125)
at ninja.i18n.MessagesImpl.getWithDefault(MessagesImpl.java:112)
at ninja.NinjaDefault.buildErrorMessage(NinjaDefault.java:443)
at ninja.NinjaDefault.getInternalServerErrorResult(NinjaDefault.java:256)
at ninja.NinjaDefault.onException(NinjaDefault.java:200)
at ninja.NinjaDefault.onRouteRequest(NinjaDefault.java:116)
at ninja.servlet.NinjaServletDispatcher.service(NinjaServletDispatcher.java:86)
at com.google.inject.servlet.ServletDefinition.doServiceImpl(ServletDefinition.java:290)
at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:280)
at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:184)
at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:89)
at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:121)
at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:133)
at ninja.servlet.NinjaServletFilter.doFilter(NinjaServletFilter.java:106)
at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:548)
at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1435)
at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)
at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1350)
at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
at org.eclipse.jetty.server.Server.handle(Server.java:516)
at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:388)
at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:633)
at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:380)
at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273)
at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375)
at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:773)
at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:905)
at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by thibaultmeyer** [comment]
Hello,

Without further information about the code that is causing problems and your dev environment, I assume that you are using the latest version of Ninja Framework with OpenJDK 8.

I reproduce a similar error. The problem is that the `Message::getWithDefault` method does not check that the default value is non-null when it goes to use it.

**Comment by asolntsev** [comment]
@thibaultmeyer yes, the latest Ninja and OpenJdk11. I didn't provide these details because I though the stack trace contains all information needed to fix the problem.
